---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: payroll-data-pv
  labels:
    app: agentic-payroll
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/payroll"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payroll-data-pvc
  namespace: payroll-system
  labels:
    app: agentic-payroll
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
